version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  lint_code:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint code
          command: npm run lint:fix

  run_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build

workflows:
  build_app:
    jobs:
      - lint_code
      - run_test:
          requires:
            - lint_code
      - build:
          requires:
            - run_test