version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  lint_code:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint code
          command: npm run lint:fix

  run_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build

  run_release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Set up git credentials
          command: |
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_NAME"
      - run:
          name: Run release
          command: npm run release

  npm_publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish --access public

workflows:
  build_app:
    jobs:
      - lint_code
      - run_test:
          requires:
            - lint_code
      - build:
          requires:
            - run_test
      - run_release:
          requires:
            - build
      - npm_publish:
          requires:
            - run_release